-- DROP TABLE IF EXISTS sounds;

CREATE TABLE sounds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    sound_uri TEXT NOT NULL,
    thumb_uri TEXT NOT NULL
);
